version: '3.4'

services:
  app:
    image: job-schedule-app
    container_name: job-schedule-app
    environment:
      - JSCH_ENV=${JSCH_ENV}
      - HTTP_PORT=${HTTP_PORT}
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}
      - AUTH_PASSWORD_SALT=${AUTH_PASSWORD_SALT}
      - AUTH_VERIFICATION_CODE_LENGTH=${AUTH_VERIFICATION_CODE_LENGTH}
      - JSCH_MONGO_URI=${JSCH_MONGO_URI}
      - JSCH_MONGO_USER=${JSCH_MONGO_USER}
      - JSCH_MONGO_PASSWORD=${JSCH_MONGO_PASSWORD}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HTTP_PORT}:8085"
    depends_on:
      - mongodb
    volumes:
      - ./.bin:/var/lib/app

  mongodb:
    image: mongo:4.4.5-bionic
    container_name: mongodb
    environment:
      - MONGO_DATA_DIR=/var/data/mongo
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./.data/mongo:/var/data/mongo
    ports:
      - 27018:27017