JSCH_ENV=production

JSCH_MONGO_URI=test
JSCH_MONGO_USER=test
JSCH_MONGO_PASSWORD=test

JWT_SIGNING_KEY=test

AUTH_PASSWORD_SALT=salt
AUTH_VERIFICATION_CODE_LENGTH=8

.EXPORT_ALL_VARIABLES:

run:
	go run cmd/app/main.go